# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kadai8' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kadai8
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'FirebaseUI'
  #pod 'FirebaseUI/Auth'
  #pod 'FirebaseUI/Google'
  #pod 'FirebaseUI/Facebook'
  #pod 'FirebaseUI/Twitter'
  #pod 'FirebaseUI/Phone'
  #pod 'FacebookSDK'
  pod 'Firebase/Core'
  #pod "Gemini"
  pod 'TextFieldEffects'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'EasySocialButton'
  pod 'Parchment'
  pod ‘DisplaySwitcher’, '~> 2.0’
  pod 'XLPagerTabStrip', '~> 9.0'
  #pod 'FBSDKLoginKit'
  pod 'PKHUD'
end
