# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'kadai8' do
#/Users/keisuke13/Desktop/kadai8_kassai/kadai8/Podfile
# Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kadai8
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'FirebaseUI'
  pod 'Firebase/Core'
  pod 'TextFieldEffects'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'EasySocialButton'
  pod 'Parchment'
  pod ‘DisplaySwitcher’, '~> 2.0’
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'PKHUD'
  pod 'FloatingPanel'

end
